# Generated by Django 3.1.4 on 2020-12-16 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JWK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('algorithm', models.CharField(blank=True, choices=[('RS256', 'RS256'), ('RS384', 'RS384'), ('RS512', 'RS512')], default='RS512', max_length=10, verbose_name='Algorithm')),
                ('_private_key', models.BinaryField(default=None, null=True, verbose_name='Private key')),
                ('public_exponent', models.IntegerField(default=65537, verbose_name='Public exponent')),
                ('key_size', models.IntegerField(choices=[(1024, '1024'), (2048, '2048'), (4096, '4096')], default=2048, verbose_name='Key size')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Key ID')),
            ],
            options={
                'verbose_name': 'JWK',
                'verbose_name_plural': 'JWKs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
